services:
  activemq:
    image: 'apache/activemq-classic:6.1.8'
    ports:
      - '61616'
  postgres:
    image: 'postgres:11'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - type: bind
        source: ./src/main/resources/docker/db/init
        target: /docker-entrypoint-initdb.d/
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

volumes:
  postgres-data: