server:
  port: 8080

spring:
  mvc:
    apiversion:
      required: true
      use:
        header: X-API-Version
  threads:
    virtual:
      enabled: true
  #  using docker-compose now, following are not required
  #  datasource:
  #    driverClassName: org.h2.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: root
  #    password: root
  #    hikari:
  #  sql:
  #    init:
  #      enabled: true
  #      schema-locations: classpath:schema/**/*.sql
  #      #data-locations: classpath:data/*/*.sql
  #  h2:
  #    console.enabled: true
  activemq:
    broker-url: vm://localhost?broker.persistent=false&broker.useShutdownHook=false
  integration:
    jdbc:
      initialize-schema: never  # never auto create integration related tables
  batch:
    jdbc:
      initialize-schema: never  # never auto create batch related tables
    job:
      enabled: false
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: false # do not auto create table for event publication

logging:
  level:
    org.springframework:
      web.socket.messaging: INFO
      messaging.simp: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
