server:
  port: 8080

spring:
  mvc:
    apiversion:
      required: true
      use:
        header: X-API-Version
  threads:
    virtual:
      enabled: true
  #  using docker-compose now, following are not required
  #  datasource:
  #    driverClassName: org.h2.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: root
  #    password: root
  #    hikari:
  #  sql:
  #    init:
  #      enabled: true
  #      schema-locations: classpath:schema/**/*.sql
  #      #data-locations: classpath:data/*/*.sql
  #  h2:
  #    console.enabled: true
  activemq:
    embedded:
      enabled: false
  #   broker-url: vm://localhost?broker.persistent=false&broker.useShutdownHook=false
  kafka:
    bootstrap-servers: localhost:9092
    #    ssl:
    #      key-store-key:
    #      key-store-location:
    #      trust-store-location:
    #      trust-store-password:
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  integration:
    jdbc:
      initialize-schema: never  # never auto create integration related tables
  batch:
    jdbc:
      initialize-schema: never  # never auto create batch related tables
    job:
      enabled: false
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: false # do not auto create table for event publication

logging:
  level:
    org.springframework:
      web.socket.messaging: INFO
      messaging.simp: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
